#!/bin/sh
set -e
if [ "$1" = "remove" ] || [ "$1" = "deconfigure" ]; then
  systemctl stop sap-fx-control-center.service >/dev/null 2>&1 || true
  systemctl disable sap-fx-control-center.service >/dev/null 2>&1 || true
fi
exit 0
